# .github/workflows/build.yml
name: Build

on: [workflow_dispatch]
#on: [push, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building .."

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ci_index: [0, 1, 2, 3]
        ci_total: [4]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          
      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 11
        with:
          browser: chrome
      - name: Generate report
        run: cd cypress && npm run posttest
        env:
          CI_TOTAL: ${{ matrix.ci_total }}
          CI_INDEX: ${{ matrix.ci_index }}
          
#       - name: Upload report
#         uses: actions/upload-artifact@v2
#         with:
#           name: cypress-cucumber-report
#           path: cypress/cucumber-report/
       
