name: Cypress tests - Manual
on: 
#   push:
#     branches:
#       - 'main'
  workflow_dispatch:

jobs:
  #test_schedule:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          browser: chrome
