#DO THE TEST EACH 6 HOURS FROM MONDAY TO FRIDAY
name: Cypress manual test
on: 
#   schedule:
#   - cron: "0 */6 * * 5"
  
#   push:
#     branches:
#      - 'main'
      
  workflow_dispatch:

jobs:

  #test_schedule:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: Install node version
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v3
        timeout-minutes: 10
        with:
          browser: chrome     

      - name: Generate report
        run: cd cypress && npm run posttest
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-cucumber-report
          path: cypress/cucumber-report/
