name: Component Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: cy_actions
          install-command: npm install
      - name: Generate report
        run: cd cy_actions && npm run test
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-cucumber-report
          path: mycypress/cypress/cucumber-report/
